version: 2

sources:
    - name: dbt_averma
      tables:
          - name: RAW_CUSTOMERS
    - name: dbt_averma
      tables:
          - name: RAW_ORDERS
    
models:
    
    - name: RAW_CUSTOMERS
      description: "A CUSTOMER dbt model"
      columns:
          - name: ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            name: first_name
            description: "The customer first name"
            tests:
                - not_null
            name: last_name
            description: "The customer last name"
            tests:
                - not_null

    - name: RAW_ORDERS
      description: "A ORDERS dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            name: cust_id
            description: "customer id"
            tests:
                - not_null
            name: order_date
            description: "order date when this order was placed"
            tests:
                - not_null
            name: status
            description: "The current status of this order"
            tests:
                - not_null

    - name: CUSTORDERS
      description: "A CUST_ORDERS dbt model"
      columns:
          - name: Customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            name: First_Name
            description: "First name"
            tests:
                - not_null
            name: Last_Name
            description: "last name"
            tests:
                - not_null
            name: First_Order_date
            description: "first order date"
            tests:
                - not_null
            name: MOST_RECENT_ORDER_DATE
            description: "recent order date"
            tests:
                - not_null
            name: NUMBER_OF_ORDERS
            description: "number of orders"
            tests:
                - not_null