version: 2

models:
    - name: RAW_CUSTOMERS
      description: "A CUSTOMER dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            name: first_name
            description: "The customer first name"
            tests:
                - not_null
            name: last_name
            description: "The customer last name"
            tests:
                - not_null

    - name: RAW_ORDERS
      description: "A ORDERS dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            name: user_id
            description: "customer id"
            tests:
                - not_null
            name: order_date
            description: "order date when this order was placed"
            tests:
                - not_null
            name: status
            description: "The current status of this order"
            tests:
                - not_null
